FROM anchore/syft:v1.50.0@sha256:1288ea4c8b38767b4e620c1e312c8cb26b6e887a99b4f07ab6cd19fc6f225026 AS syft
FROM anchore/grype:v0.116.1@sha256:1e71065c0a4cff3e6bd3b8add525ffac4343eb4971694eb90a31cf6d4d3e85db AS grype

FROM mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm@sha256:0d29e5fdc64f8397cd502223e0c4679f1e60877ca0fd2db4f2e2e0028e4271af

COPY --from=syft /syft /usr/local/bin/syft
COPY --from=grype /grype /usr/local/bin/grype

USER root

ARG GRYPE_DB_URL="https://grype.anchore.io/databases/v6/vulnerability-db_v6.1.9_2026-08-13T00:26:15Z_1786603170.tar.zst"
ARG GRYPE_DB_SHA256="f5b1ce5bb521d0abf5f030eca10f6a675d6179717a418258529c245d470a5326"
ARG TARGETARCH="amd64"

ENV GRYPE_DB_CACHE_DIR=/opt/grype-db \
    GRYPE_DB_AUTO_UPDATE=false \
    GRYPE_DB_VALIDATE_AGE=false \
    GRYPE_CHECK_FOR_APP_UPDATE=false \
    SYFT_CHECK_FOR_APP_UPDATE=false

RUN case "$TARGETARCH" in \
      amd64) \
        ZSTD_SHA256="3f6f833ae2fd533a0c9238310aef1148f51a64aa5d5f1278451ddc793d4d6d15"; \
        GIT_LFS_SHA256="633a69f57a01eb3dd8e4bf8e191296793c5305e90e3d4584115fba2815081383" \
        ;; \
      arm64) \
        ZSTD_SHA256="97a58383b0ad55cc8183e59cbb112f2eb55c3dc1e90de816fa5cfb983d5c2ff0"; \
        GIT_LFS_SHA256="b6d69c986d219a5000a0f3c33a20c619a7f83d4752c163c35a588152eb71b01e" \
        ;; \
      *) printf 'Unsupported architecture: %s\n' "$TARGETARCH" >&2; exit 1 ;; \
    esac \
    && ZSTD_PACKAGE="zstd_1.5.4+dfsg2-5_${TARGETARCH}.deb" \
    && curl --fail --location --retry 3 \
      --output "/tmp/$ZSTD_PACKAGE" \
      "https://deb.debian.org/debian/pool/main/libz/libzstd/$ZSTD_PACKAGE" \
    && printf '%s  %s\n' "$ZSTD_SHA256" "/tmp/$ZSTD_PACKAGE" | sha256sum --check --strict \
    && dpkg --install "/tmp/$ZSTD_PACKAGE" \
    && rm --force "/tmp/$ZSTD_PACKAGE" \
    && GIT_LFS_PACKAGE="git-lfs_3.3.0-1+deb12u1_${TARGETARCH}.deb" \
    && curl --fail --location --retry 3 \
      --output "/tmp/$GIT_LFS_PACKAGE" \
      "https://deb.debian.org/debian/pool/main/g/git-lfs/$GIT_LFS_PACKAGE" \
    && printf '%s  %s\n' "$GIT_LFS_SHA256" "/tmp/$GIT_LFS_PACKAGE" | sha256sum --check --strict \
    && dpkg --install "/tmp/$GIT_LFS_PACKAGE" \
    && rm --force "/tmp/$GIT_LFS_PACKAGE" \
    && mkdir --parents /opt/grype-db

COPY fixtures/grype-db.tar.zst /tmp/grype-db.tar.zst

RUN printf '%s  %s\n' "$GRYPE_DB_SHA256" /tmp/grype-db.tar.zst | sha256sum --check --strict \
    && grype db update \
    && rm --force /tmp/grype-db.tar.zst \
    && chmod --recursive a+rX /opt/grype-db \
    && grype db status

USER node
